apiVersion: v1
kind: Service
metadata:
  name: lab8-rsvp
  labels:
    app: lab8-rsvp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: web-port
    protocol: TCP
  selector:
    app: lab8-rsvp