apiVersion: v1
kind: Service
metadata:
  name: lab6-web-service
  labels:
    run: lab6-web-service
    
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
  selector:
    k8s-app: lab6-webserver